config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'posts#index'
  resources :posts, only: [:index,:create]
  resources :users, only: [:show] do
    resources :follows, only: [:create,:destroy]
    get 'user_following' ,to: 'follows#user_following'
    get 'user_followed' ,to: 'follows#user_followed'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord

  # relationship（中間テーブル）とのアソシエーション
  has_many :relationships
  # userモデルとのアソシエーション
  has_many :users            , through: :relationships
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content         , presence:true, presence: { message: "can't be blank" }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :following
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname             , presence:true
  

  has_many :posts

  # relationship（中間テーブル）とのアソシエーション
  has_many :relationships
  # followingモデルとのアソシエーション
  has_many :followings       , through: :relationships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_user
  before_action :set_following  ,only: [:user_following]
  before_action :set_followed   ,only: [:user_followed]

  def create
    @follow = Relationship.create(user_id: current_user.id, following_id: params[:user_id])

    set_following
    set_followed
  end

  def destroy
    follow = Relationship.find(params[:id])
    follow.destroy

    set_following
    set_followed 
  end

  def user_following
  end

  def user_followed
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_following
    # @userがフォローしている人たち
    @following = @user.followings

    # @following = Relationship.where(user_id: @user.id)
  end

  def set_followed
    # @userをフォローしている人たち
    @followed = @user.followers    

    # @followed = Relationship.where(following_id: @user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at:"DESC")
    @post = Post.new
  end

  def create
    @post = Post.new(params_content)
    @posts = Post.all.order(created_at:"DESC")
    if @post.save
      redirect_to root_path
    else
      render :index
    end
  end

  private
  
  def params_content
    params.require(:post).permit(:content).merge(user_id:current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    super
  end

  # POST /resource
  def create
    # 止まるか確認
    # binding.pry

    super

    # この時点で@userに新規登録したデータが入っているかの確認
    # binding.pry

    # followingsテーブルへの保存
    Following.create(nickname:@user.nickname,user_id:@user.id)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts

    @follow = Relationship.find_by(user_id: current_user.id, following_id: @user)
    
    # @userがフォローしている人たち
    @following = @user.followings
    # @following = Relationship.where(user_id: @user.id)
  
    # @userをフォローしている人たち
    @followed = @user.followers
    # @followed = Relationship.where(following_id: @user.id)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/_follow.html.erb
<div class="user-header">
  <div class="user-name">
    <%= "#{@user.nickname}さんの詳細ページ" %>
  </div>

  <div class="follow-unfollow">
    <% if @user != current_user %>
      <% if @follow %>
        <%= link_to user_follow_path(@user, @follow), method: :delete, remote: true, class: :unfollow_btn do %>
          <div class="unfollow">
            フォロー解除
          </div>
        <% end %>
      <% else %>
        <%= link_to user_follows_path(@user), method: :post, remote: true, class: :follow_btn do %>
          <div class="follow">
            フォローする
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="user-update">
        プロフィールを編集
      </div>
    <% end %>
  </div>
</div>

<div class="follow-length">
  <div class="user-follow">
      <%= link_to "フォロー #{@following.length}", user_user_following_path(@user) ,class: :user_follow_length %>
  </div>

  <div class="user-follower">
    <%= link_to "フォロワー #{@followed.length}", user_user_followed_path(@user) ,class: :user_follow_length %>
  </div>
</div>

app/views/follows/create.js.erb
document.getElementById('user-follow').innerHTML = "<%= j(render 'follow') %>"

app/views/follows/destroy.js.erb
document.getElementById('user-follow').innerHTML = "<%= j(render 'follow') %>"

app/views/follows/user_followed.html.erb
<div class="user-follow-lists">
  <div class="user-show">
    <%= link_to "#{@user.nickname}さん詳細ページへ戻る",user_path(@user.id) %><br> 
  </div>

  <div class="user-name">
    <%= "#{@user.nickname}さんをフォローしているユーザー"%><br> 
  </div>

  <div class="non-follow">
    <% if @followed.length == 0 %>
      <%= "#{@user.nickname}さんをフォローしているユーザーはいません"%>
    <% end %>
  </div>

  <div class="follow-lists">
    <% @followed.each do |followed| %>
      <div class="post">
        ユーザー名：<%= link_to followed.nickname,user_path(followed.id) %><br> 
      </div>
    <% end %>
  </div>
</div>

app/views/follows/user_following.html.erb
<div class="user-follow-lists">
  <div class="user-show">
    <%= link_to "#{@user.nickname}さん詳細ページへ戻る",user_path(@user.id) %><br> 
  </div>

  <div class="user-name">
    <%= "#{@user.nickname}さんがフォローしているユーザー"%><br> 
  </div>

  <div class="non-follow">
    <% if @following.length == 0 %>
      <%= "#{@user.nickname}さんは誰もフォローしていません"%>
    <% end %>
  </div>

  <div class="follow-lists">
    <% @following.each do |following| %>
      <div class="post">
        ユーザー名：<%= link_to following.nickname,user_path(following.id) %><br> 
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>FollowApp</h1>

こんにちは、
<%= link_to "#{current_user.nickname}さん" ,user_path(current_user.id) %><br>
<%= link_to "ログアウト",destroy_user_session_path,method: :delete, class: :nav__logout %> 


<%= form_with model:@post, id:"form" ,local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <%= f.text_field :content ,id:"content" %>
  <%= f.submit '投稿する',id: "submit" %>
<% end %>

<% @posts.each do |post| %>
  <div class="post">
     投稿者：<%= link_to post.user.nickname,user_path(post.user.id) %><br> 
    <div class="post-date">
      投稿日時：<%= l post.created_at %>
    </div>
    <div class="post-content">
      投稿内容：<%= post.content %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="user-wrap">

  <div id="user-follow">

    <div class="user-header">
      <div class="user-name">
        <%= "#{@user.nickname}さんの詳細ページ" %>
      </div>

      <div class="follow-unfollow">
        <% if @user != current_user %>
          <% if @follow %>
            <%= link_to user_follow_path(@user, @follow), method: :delete, remote: true, class: :unfollow_btn do %>
              <div class="unfollow">
                フォロー解除
              </div>
            <% end %>
          <% else %>
            <%= link_to user_follows_path(@user), method: :post, remote: true, class: :follow_btn do %>
              <div class="follow">
                フォローする
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="user-update">
            プロフィールを編集
          </div>
        <% end %>
      </div>
    </div>

    <div class="follow-length">
      <div class="user-follow">
        <%= link_to "フォロー #{@following.length}", user_user_following_path(@user) ,class: :user_follow_length %>
      </div>

      <div class="user-follower">
        <%= link_to "フォロワー #{@followed.length}", user_user_followed_path(@user) ,class: :user_follow_length %>
      </div>
    </div>

  </div>


  <div class="user-show">
    <%= link_to "トップページに戻る", root_path %>

    <div class="user-show-like"> 
      <%="#{@user.nickname}さんの投稿" %>
    </div>

    <% @posts.each do |post| %>
      <div class="post">
        <div class="post-date">
          投稿日時：<%= l post.created_at %>
        </div>
        <div class="post-content">
          投稿者：<%= post.user.nickname %><br>
          投稿内容：<%= post.content %>
        </div>
      </div>
    <% end %>
  </div>

</div>